const cars = [
    {
        id: 1,
        name: "Koenigsegg",
        rating: 4,
        type: "Sport",
        Reviewers: 150,
        price: 99,
        fuelCapacity: 90,
        transmission: "Manual",
        passengers: 2,
        image: "/cars/car-1.svg",
        title: "Koenigsegg",
        text: "Experience the thrill of the open road like never before with the Koenigsegg. This high-performance sports car is designed to deliver ",
    },
    {
        id: 2,
        name: "Nissan GT-R",
        rating: 4,
        type: "Sport",
        Reviewers: 170,
        price: 80,
        fuelCapacity: 80,
        transmission: "Manual",
        passengers: 2,
        image: "/cars/Car-2.svg",
        title: "Nissan GT-R",
        text: "Experience the thrill of the open road like never before with the Nissan GT-R. This high-performance sports car is designed to deliver ",
    },
    {
        id: 3,
        name: "Rolls-Royce",
        rating: 4,
        type: "Sedan",
        Reviewers: 180,
        price: 96,
        fuelCapacity: 70,
        transmission: "Manual",
        passengers: 4,
        image: "/cars/Car-3.svg",
        title: "Rolls-Royce",
        text: "Experience the thrill of the open road like never before with the Rolls-Royce. This high-performance sports car is designed to deliver ",
    },
    {
        id: 4,
        name: "Nissan GT-R",
        rating: 4,
        type: "Sport",
        Reviewers: 190,
        price: 80,
        fuelCapacity: 80,
        transmission: "Manual",
        passengers: 2,
        image: "/cars/Car-4.svg",
        title: "Nissan GT-R",
        text: "Experience the thrill of the open road like never before with the Nissan GT-R. This high-performance sports car is designed to deliver ",
    },
    {
        id: 5,
        rating: 4,
        name: "All New Rush",
        type: "SUV",
        Reviewers: 200,
        price: 72,
        fuelCapacity: 70,
        transmission: "Manual",
        passengers: 6,
        image: "/cars/Car-5.svg",
        title: "All New Rush",
        text: "Experience the thrill of the open road like never before with the All New Rush. This high-performance sports car is designed to deliver ",
    },
    {
        id: 6,
        name: "CR-V",
        rating: 3,
        type: "SUV",
        Reviewers: 210,
        price: 80,
        fuelCapacity: 80,
        transmission: "Manual",
        passengers: 6,
        image: "/cars/Car-6.svg",
        title: "CR-V",
        text: "Experience the thrill of the open road like never before with the CR-V. This high-performance sports car is designed to deliver ",
    },
    {
        id: 7,
        name: "All New Terios",
        rating: 4,
        type: "SUV",
        Reviewers: 110,
        price: 74,
        fuelCapacity: 90,
        transmission: "Manual",
        passengers: 6,
        image: "/cars/Car-7.svg",
        title: "All New Terios",
        text: "Experience the thrill of the open road like never before with the All New Terios. This high-performance sports car is designed to deliver ",
    },
    {
        id: 8,
        name: "CR-V",
        rating: 4,
        type: "SUV",
        Reviewers: 100,
        price: 80,
        fuelCapacity: 80,
        transmission: "Manual",
        passengers: 6,
        image: "/cars/Car-8.svg",
        title: "CR-V",
        text: "Experience the thrill of the open road like never before with the CR-V. This high-performance sports car is designed to deliver ",
    },
    {
        id: 9,
        name: "MG ZX Exclusive",
        rating: 4,
        type: "Hatchback",
        Reviewers: 120,
        price: 76,
        fuelCapacity: 70,
        transmission: "Manual",
        passengers: 4,
        image: "/cars/Car-9.svg",
        title: "MG ZX Exclusive",
        text: "Experience the thrill of the open road like never before with the MG ZX Exclusive. This high-performance sports car is designed to deliver ",
    },
    {
        id: 10,
        name: "New MG ZS",
        rating: 5,
        type: "SUV",
        Reviewers: 130,
        price: 80,
        fuelCapacity: 80,
        transmission: "Manual",
        passengers: 6,
        image: "/cars/image 7.svg",
        title: "New MG ZS",
        text: "Experience the thrill of the open road like never before with the New MG ZS. This high-performance sports car is designed to deliver ",
    },
    {
        id: 11,
        name: "MG ZX Excite",
        rating: 3,
        type: "Hatchback",
        Reviewers: 140,
        price: 74,
        fuelCapacity: 90,
        transmission: "Manual",
        passengers: 4,
        image: "/cars/image 8.svg",
        title: "MG ZX Excite",
        text: "Experience the thrill of the open road like never before with the MG ZX Excite. This high-performance sports car is designed to deliver.",
    },
    {
        id: 12,
        name: "New MG ZS",
        rating: 4,
        type: "SUV",
        Reviewers: 150,
        price: 80,
        fuelCapacity: 80,
        transmission: "Manual",
        passengers: 6,
        image: "/cars/car.svg",
        title: "New MG ZS",
        text: "Experience the thrill of the open road like never before with the New MG ZS. This high-performance sports car is designed to deliver.",
    },
];

export default cars;