const reviews = [
    {
        id: 1,
        name: "John Doe",
        designation: "CEO of XYZ Company",
        rating: 5,
        review: "Great car! Highly recommended for family trips. It's been a great time using this car.",
        date: "21 Jul 2023",
    },
    {
        id: 2,
        name: "Jane Smith",
        designation: "Manager at ABC Company",
        rating: 4,
        review: "Good car, but could be better. The mileage is not as expected.",
        date: "12 Mar 2022",
    },
    {
        id: 3,
        name: "Bob Johnson",
        designation: "Engineer at DEF Company",
        rating: 3,
        review: "Average car, nothing special. The features are outdated.",
        date: "27 Oct 2022",
    },
    {
        id: 4,
        name: "Alice Williams",
        designation: "Doctor at GHI Hospital",
        rating: 5,
        review: "Excellent car! Very comfortable and smooth to drive.",
        date: "07 Feb 2015",
    },
    {
        id: 5,
        name: "Charlie Brown",
        designation: "Teacher at JKL School",
        rating: 4,
        review: "Nice car, good value for money. The interior is spacious.",
        date: "15 May 2020",
    },
    {
        id: 6,
        name: "Diana Prince",
        designation: "Lawyer at MNO Firm",
        rating: 5,
        review: "Fantastic car! The performance is top-notch and the safety features are great.",
        date: "06 Jun 2018",
    },
    {
        id: 7,
        name: "Ethan Hunt",
        designation: "Spy at NOP Agency",
        rating: 4,
        review: "Decent car, but the infotainment system is a bit slow.",
        date: "01 Jan 2021",
    },
    {
        id: 8,
        name: "Fiona Glenanne",
        designation: "Agent at OPQ Agency",
        rating: 5,
        review: "Amazing car! The handling is superb and the ride quality is excellent.",
        date: "19 Nov 2019",
    },
    {
        id: 9,
        name: "George Clooney",
        designation: "Actor at RST Studio",
        rating: 4,
        review: "Good car, but the price is a bit high for the features offered.",
        date: "03 Apr 2017",
    },
    {
        id: 10,
        name: "Hannah Montana",
        designation: "Singer at STU Records",
        rating: 5,
        review: "Love this car! It's stylish, comfortable, and fun to drive.",
        date: "11 Dec 2016",
    },
    {
        id: 11,
        name: "Ian Fleming",
        designation: "Author at TUV Publishing",
        rating: 4,
        review: "Nice car, but the boot space is limited. Otherwise, it's a great vehicle.",
        date: "23 Mar 2014",
    },
    {
        id: 12,
        name: "Julia Roberts",
        designation: "Actress at UVW Studio",
        rating: 5,
        review: "Excellent car! The build quality is solid and the driving experience is smooth.",
        date: "18 Aug 2013",
    },
    {
        id: 13,
        name: "Kevin McCallister",
        designation: "Student at WXY School",
        rating: 3,
        review: "It's an okay car. Nothing extraordinary, but it gets the job done.",
        date: "13 Jan 2022",
    },
    {
        id: 14,
        name: "Lisa Simpson",
        designation: "Student at XYZ School",
        rating: 5,
        review: "Brilliant car! The technology is advanced and the performance is impressive.",
        date: "14 Jan 2022",
    },
    {
        id: 15,
        name: "Michael Scott",
        designation: "Manager at ABCD Company",
        rating: 4,
        review: "Good car for the price. The AC works well in hot weather.",
        date: "25 Jan 2022",
    },
    {
        id: 16,
        name: "Nancy Drew",
        designation: "Detective at EFGH Agency",
        rating: 5,
        review: "Fantastic car for long drives. Very reliable and comfortable.",
        date: "06 Feb 2022",
    },
    {
        id: 17,
        name: "Oscar Wilde",
        designation: "Writer at IJKL Publishing",
        rating: 4,
        review: "Elegant car with a smooth ride. The design is quite appealing.",
        date: "17 Mar 2022",
    },
    {
        id: 18,
        name: "Pam Beesly",
        designation: "Receptionist at MNOP Company",
        rating: 3,
        review: "It's a decent car for daily commuting. Nothing fancy, but it works.",
        date: "28 Apr 2022",
    },
    {
        id: 19,
        name: "Quentin Tarantino",
        designation: "Director at QRST Studio",
        rating: 5,
        review: "Awesome car! The driving dynamics are thrilling and the sound system is great.",
        date: "09 May 2022",
    },
    {
        id: 20,
        name: "Rachel Green",
        designation: "Fashion Designer at UVWX Company",
        rating: 4,
        review: "Stylish car with a modern interior. It turns heads on the road.",
        date: "20 Jun 2022",
    },
    {
        id: 21,
        name: "Steve Rogers",
        designation: "Captain at YZAB Agency",
        rating: 5,
        review: "Excellent car with great safety features. Feels very secure to drive.",
        date: "01 Jul 2022",
    },
    {
        id: 22,
        name: "Tina Fey",
        designation: "Comedian at BCDE Company",
        rating: 4,
        review: "Fun car to drive. The handling is responsive and the acceleration is good.",
        date: "12 Aug 2022",
    },
    {
        id: 23,
        name: "Ursula K. Le Guin",
        designation: "Author at FGHI Publishing",
        rating: 5,
        review: "A masterpiece of engineering. The ride quality is simply superb.",
        date: "23 Sep 2022",
    },
    {
        id: 24,
        name: "Victor Frankenstein",
        designation: "Scientist at JKLI Company",
        rating: 3,
        review: "It's a functional car, but the design looks a bit outdated.",
        date: "04 Oct 2022",
    },
    {
        id: 25,
        name: "Wendy Darling",
        designation: "Student at MNOP School",
        rating: 4,
        review: "Nice car for family outings. Spacious and comfortable for kids.",
        date: "15 Nov 2022",
    },
    {
        id: 26,
        name: "Xena Warrior",
        designation: "Warrior at QRST Agency",
        rating: 5,
        review: "Excellent car! The performance is top-notch and the safety features are great.",
        date: "26 Dec 2022",
    },
    {
        id: 27,
        name: "Yoda",
        designation: "Jedi Master at STUV Agency",
        rating: 4,
        review: "Good car, but the mileage is not as expected.",
        date: "07 Jan 2023",
    },
    {
        id: 28,
        name: "Zorro",
        designation: "Swordsman at WXYZ Agency",
        rating: 5,
        review: "Fantastic car! The handling is superb and the ride quality is excellent.",
        date: "18 Feb 2023",
    },
    {
        id: 29,
        name: "Alice in Wonderland",
        designation: "Adventurer at ABCD Agency",
        rating: 4,
        review: "Nice car, good value for money. The interior is spacious.",
        date: "29 Mar 2023",
    },
    {
        id: 30,
        name: "Bob the Builder",
        designation: "Builder at EFGH Agency",
        rating: 3,
        review: "It's an okay car. Nothing extraordinary, but it gets the job done.",
        date: "10 Apr 2023",
    },
    {
        id: 31,
        name: "Charlie Chaplin",
        designation: "Comedian at IJKL Agency",
        rating: 5,
        review: "Brilliant car! The technology is advanced and the performance is impressive.",
        date: "21 May 2023",
    },
    {
        id: 32,
        name: "Diana Ross",
        designation: "Singer at MNOP Agency",
        rating: 4,
        review: "Good car for the price. The AC works well in hot weather.",
        date: "01 Jun 2023",
    },
    {
        id: 33,
        name: "Ethan Hawke",
        designation: "Actor at QRST Agency",
        rating: 5,
        review: "Fantastic car for long drives. Very reliable and comfortable.",
        date: "12 Jul 2023",
    },
    {
        id: 34,
        name: "Fiona Apple",
        designation: "Musician at UVWX Agency",
        rating: 4,
        review: "Elegant car with a smooth ride. The design is quite appealing.",
        date: "23 Aug 2023",
    },
    {
        id: 35,
        name: "George Harrison",
        designation: "Musician at YZAB Agency",
        rating: 3,
        review: "It's a decent car for daily commuting. Nothing fancy, but it works.",
        date: "03 Sep 2023",
    },
    {
        id: 36,
        name: "Hannah Montana",
        designation: "Singer at BCDE Agency",
        rating: 5,
        review: "Awesome car! The driving dynamics are thrilling and the sound system is great.",
        date: "14 Oct 2023",
    },
    {
        id: 37,
        name: "Ian McKellen",
        designation: "Actor at FGHI Agency",
        rating: 4,
        review: "Stylish car with a modern interior. It turns heads on the road.",
        date: "25 Nov 2023",
    },
    {
        id: 38,
        name: "Julia Child",
        designation: "Chef at JKLI Agency",
        rating: 5,
        review: "Excellent car with great safety features. Feels very secure to drive.",
        date: "06 Dec 2023",
    },
    {
        id: 39,
        name: "Kevin Bacon",
        designation: "Actor at MNOP Agency",
        rating: 4,
        review: "Fun car to drive. The handling is responsive and the acceleration is good.",
        date: "17 Jan 2024",
    },
    {
        id: 40,
        name: "Lisa Kudrow",
        designation: "Actress at QRST Agency",
        rating: 5,
        review: "A masterpiece of engineering. The ride quality is simply superb.",
        date: "28 Feb 2024",
    },
    {
        id: 41,
        name: "Michael Jordan",
        designation: "Athlete at UVWX Agency",
        rating: 3,
        review: "It's a functional car, but the design looks a bit outdated.",
        date: "09 Mar 2024",
    },
    {
        id: 42,
        name: "Nancy Sinatra",
        designation: "Singer at YZAB Agency",
        rating: 4,
        review: "Nice car for family outings. Spacious and comfortable for kids.",
        date: "20 Apr 2024",
    },
    {
        id: 43,
        name: "Oscar De La Hoya",
        designation: "Boxer at BCDE Agency",
        rating: 5,
        review: "Excellent car! The performance is top-notch and the safety features are great.",
        date: "01 May 2024",
    },
    {
        id: 44,
        name: "Pamela Anderson",
        designation: "Model at FGHI Agency",
        rating: 4,
        review: "Good car, but the mileage is not as expected.",
        date: "12 Jun 2024",
    },
    {
        id: 45,
        name: "Quentin Tarantino",
        designation: "Director at JKLI Agency",
        rating: 5,
        review: "Fantastic car! The handling is superb and the ride quality is excellent.",
        date: "23 Jul 2024",
    },
    {
        id: 46,
        name: "Rachel Maddow",
        designation: "Journalist at MNOP Agency",
        rating: 4,
        review: "Nice car, good value for money. The interior is spacious.",
        date: "04 Aug 2024",
    },
    {
        id: 47,
        name: "Steve Martin",
        designation: "Comedian at QRST Agency",
        rating: 3,
        review: "It's an okay car. Nothing extraordinary, but it gets the job done.",
        date: "15 Sep 2024",
    },
    {
        id: 48,
        name: "Tina Turner",
        designation: "Singer at UVWX Agency",
        rating: 5,
        review: "Brilliant car! The technology is advanced and the performance is impressive.",
        date: "26 Oct 2024",
    },
    {
        id: 49,
        name: "Uma Thurman",
        designation: "Actress at YZAB Agency",
        rating: 4,
        review: "Good car for the price. The AC works well in hot weather.",
        date: "07 Nov 2024",
    },

]

export default reviews
